version: '3'

services:
  price_it_frontend:
    container_name: price_it_frontend
    build: .
    restart: unless-stopped
    ports:
      - 5173:5173
    volumes:
      - .:/src
      - /src/node_modules