name: Build Frontend & Test

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:  
      LOCAL_SERVER_PORT: ${{ secrets.LOCAL_SERVER_PORT }}
      PORT: ${{ secrets.PORT }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      VITE_AUTH_BASE_URL: ${{ secrets.VITE_AUTH_BASE_URL }}
      VITE_SEARCH_BASE_URL: ${{ secrets.VITE_SEARCH_BASE_URL }}
      DOCKER_SERVER_PORT: ${{ secrets.DOCKER_SERVER_PORT }}

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: "18"
        
    - name: Install Node Dependencies
      run: npm install
      
    - name: Create empty .env file (required by docker-compose)
      run: touch .env
      
    - name: Start containers
      run: docker-compose up -d --build
      
    - name: Wait for containers to start
      run: sleep 20s

#    - name: Run Unit Tests
#      run: npm test
      
    - name: Stop containers and remove volumes
      run: docker-compose down -v
